version: '3.8'

services:
  app:
    build: .
    container_name: mon-portfolio-app
    ports:
      - "30:30"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:30/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s 